Delete Subject Button for Superuser
chop-dbhi/biorepo-portal pull request #298
Opened 2021-04-06 13:18 UTC by EndlessThoughts

The delete subject button is rendering on the protocol menu page. Upon clicking the button, you are met with a drop down list (which is rendering the correct subjects from the specific protocol) and a delete and cancel button below it.

2021-04-06 15:50 UTC, szh2425 commented on react_ui/actions/subject.js
> +
Remove extra spaces

2021-04-06 17:26 UTC, szh2425 commented on react_ui/components/SubjectSelect/DeleteForm.js
> +    //remove active subject from subject list. Limits ability for user to relate a subject to itself
remove comment since it doesn't apply

2021-04-06 17:50 UTC, szh2425 commented on react_ui/components/SubjectSelect/DeleteForm.js
> +    newFormErrors: state.subject.newFormErrors,
These 3 properties don't appear in the DeleteForm.propTypes declaration above - consider removing since they're not in use, or updating propTypes to include these properties if relevant to the deleteForm.

2021-04-06 17:51 UTC, szh2425 commented on react_ui/components/SubjectView/index.js
> +
Remove extra line

2021-04-06 18:08 UTC, szh2425 commented on package-lock.json
> +{
This file is autogenerated by npm! Please remove and add `package-lock.json` to `.gitignore` (more info about [gitignore](https://git-scm.com/docs/gitignore) if needed)

2021-04-06 18:59 UTC, EndlessThoughts commented on react_ui/actions/subject.js
> +function setNewSubjectFormErrors(errors) {
Yes it should be. I have changed it now.

2021-04-06 19:00 UTC, EndlessThoughts commented on react_ui/actions/subject.js
> +
Extra spaces have been removed.

2021-04-06 20:48 UTC, EndlessThoughts commented on react_ui/components/SubjectSelect/DeleteForm.js
> +                        styles={this.state.relatedSubErr ? errorStyle : {}}
relatedSubErr is in subFamEditView in checkRelDataEntry, so I created a checkDeleteSubEntry and declared deleteSubErr in state. Please let me know if my implementation was created.

2021-04-06 20:50 UTC, EndlessThoughts commented on react_ui/components/SubjectSelect/DeleteForm.js
> +  subject: PropTypes.object,
I have removed subject from the DeleteForm.propTypes.

2021-04-06 20:51 UTC, EndlessThoughts commented on react_ui/components/SubjectSelect/DeleteForm.js
> +    newFormErrors: state.subject.newFormErrors,
I have removed this properties as well because they are not relevant to the component.

2021-04-06 20:53 UTC, EndlessThoughts commented on react_ui/components/SubjectView/index.js
> +
I have removed the extra line.

2021-04-06 20:56 UTC, EndlessThoughts commented on package-lock.json
> +{
Could you explain this in more depth?

2021-04-09 16:37 UTC, szh2425 requested changes

2021-04-13 14:16 UTC, szh2425 requested changes
Just one minor change and you'll be all set for this PR. Awesome job learning and applying react/redux concepts. Woo!

2021-04-13 14:16 UTC, szh2425 commented on react_ui/components/SubjectSelect/DeleteForm.js
> +    if(subjects !=null){
@EndlessThoughts I got your message on slack about how the drop down list can handle on its own when there aren't any options. That's great! In that case, no need to wrap this in conditional logic, please remove `if(subjects != null)` part.

2021-04-13 14:16 UTC, szh2425 commented on react_ui/components/SubjectSelect/DeleteForm.js
> +  handleDeleteClick(e){
Nice update of wording!!

2021-04-13 15:21 UTC, szh2425 approved these changes
LGTM - woo! 

Please make sure to do a `squash and merge` (as opposed to just merge) which condenses all the commits to just one commit that contains all of the changes. We always do squash and merge because it makes for a neater git history. Afterwards, checkout `dev-kyle` branch in your local, and do a `git pull`, then feel free to create a new branch like `git checkout -b krojasp2` for the delete confirmation work!

2021-04-13 16:03 UTC, merged