Deletion Confirmation
chop-dbhi/biorepo-portal pull request #301
Opened 2021-04-15 18:19 UTC by EndlessThoughts

2021-04-20 15:54 UTC, szh2425 requested changes
Sorry for the delay Kyle but left a first round of comments. Nice job getting the delete confirmation to render! 

Because I'm still learning react myself, some of my comments are just questions for my own knowledge, but I hope they help you think about the code more too. There's something about the way props and state are defined and used in both the `DeleteForm` and `DeleteConfirmationForm` that I think could be simplified and made clearer. I'm not exactly sure how though (perhaps utilizing the `activeSubject` property rather than manually passing in `theSubject`?). I will think about this more so I can be more explicit in what I mean, but if you have insights as well, please feel free to share.

I also noticed in my local BRP that the first time the DeleteForm renders and I choose a subject to delete, the DeleteConfirmation will appear for like half a second before closing the component completely. The DeleteConfirmation works as expected though on subsequent renders. A minor bug to look into - and I can show you what I mean if this isn't happening on your local.

2021-04-20 15:54 UTC, szh2425 commented on react_ui/actions/subject.js
> +    .then(checkResponse)
Nice, you're checking that the API call returns at least some sort of success code. What happens though if checkResponse returns an error? Consider adding a `.catch` block at the end of these async calls so that errors are properly handled.

2021-04-21 20:20 UTC, szh2425 requested changes

2021-04-21 20:20 UTC, szh2425 commented on react_ui/components/SubjectSelect/DeleteForm.js
> +                        {this.props.subject.deleteSubjectConfirmationMode ? <DeletionConfirmation theSubject={this.state.chooseSubject}/>: <div />}
Rather than passing in the chosen subject as an argument to the DeleteConfirmation component : `<DeleteConfirmation theSubject={this.state.chooseSubject} />` , is there a way to utilize the redux store to implicitly pass in chosen subject? Perhaps utilize `this.subject.activeSubject` in the handleSubjectSelect function in the deleteForm - similar to how it's done [here](https://github.com/chop-dbhi/biorepo-portal/blob/b45aa56754c14066e3a7ac7a4f8bea842b20f318/react_ui/components/SubjectSelect/index.js#L83)? 

Just curious because  `protocol` isn't explicitly being passed in as an argument to DeleteConfirmation, but it still exists as a prop. I wonder if we could do the same with `theSubject`. 

However, I understand this might mean needing to refactor the way DeleteForm updates state, and might be more complex than what it's worth. Just wanted to call it out though as a consideration and I'd love to hear your thoughts!

2021-04-21 20:20 UTC, szh2425 commented on react_ui/components/SubjectSelect/DeleteForm.js
> +                        {this.props.subject.deleteSubjectConfirmationMode ? <DeletionConfirmation theSubject={this.state.chooseSubject}/>: <div />}
Also another thought - if you decide to stick with the current method of passing in the prop as an argument rather than updating and using `subject.activeSubject` that exists in the redux store, instead of calling it `theSubject`, can we rename to just `subject`? So `<DeleteConfirmation subject={this.state.chooseSubject} />` 

You'd have to remove [this line](https://github.com/chop-dbhi/biorepo-portal/blob/1314b12bde62f6edc5b1cdd944c3d4d2eda5098c/react_ui/components/SubjectSelect/DeletionConfirmation.js#L91) in `mapStateToProps` in order to this but that's okay since you're not using the `subject` state stored in redux anyway!

2021-04-27 14:29 UTC, szh2425 requested changes
Nice work Kyle - the only thing is the alert box for unauthorized user doesn't show up on Safari. Feel free to address the error Safari returned or implement a new way to render the message to users.

2021-04-27 14:29 UTC, szh2425 commented on react_ui/actions/subject.js
> +  window.alert("Error: You are not authorized to delete subjects in this protocol.");
I saw the alert message using chrome, but not with Safari - I got the following error:
<img width="1508" alt="Screen Shot 2021-04-27 at 10 07 15 AM" src="https://user-images.githubusercontent.com/33664901/116258499-0268c480-a743-11eb-9e3b-084761dbcc59.png">

 Would you consider rendering this message in another way? Perhaps displaying directly in the `DeleteConfirmation` component, or creating a new component?

2021-04-27 14:32 UTC, szh2425 commented on react_ui/actions/subject.js
> +export function fetchDeleteSubject(protocolId, subjectId) {
@EndlessThoughts maybe rename this func to just `deleteSubject`?

2021-05-04 11:42 UTC, szh2425 requested changes
For not authorized cases, the window alert for success comes up before the window alert for "You are not authorized..". It could just be the case that you need to chain the Success alert message to the dispatch functions. But I think the preferred way to do this would be for the DeleteConfirmation component to receive the error message from the redux action and depending on if it's successful or not, either render the error message or sucess message in the window alert within the component itself. We should try to limit window alerts, and any type of display in general to the `components/` folder so that the code is not disjointed (code in `actions/` should strictly stick to being API/function based).

2021-05-04 11:42 UTC, szh2425 commented on react_ui/actions/subject.js
> +  throw error;
Hm, as we talked about before, there are many status codes and error responses one can receive from the API. You can read about the common ones [here](https://restfulapi.net/http-status-codes/). Even though it's probably likely, it won't always be the case that a user can't delete a subject because of authorization issues. Is there a way to generalize this code so that you handle more than just the authorization error? Or at the very least, make sure that when the window alert for not authorized comes up, we make sure its really for 403 errors? I can explain more if this is confusing.

2021-05-04 11:46 UTC, szh2425 commented on react_ui/actions/subject.js
> +  throw error;
This comment can be negated in favor of the first PR comment above about keeping window.alerts() within the code in the `components` directory. If you just throw the error in this redux function, how can we catch it in the component and display the error window alert there?

2021-05-04 14:58 UTC, alexanderkgonzalez commented on react_ui/actions/subject.js
> +  throw error;
@szh2425 Just looked through the EHB code....it's pretty liberal with its use of 403. It throws it out in all cases where a subject is not authorized. 
[https://github.com/chop-dbhi/ehb-service/blob/62f26cbb1495026caf37e1c326a593253b88bdd9/ehb_service/apps/api/middleware.py#L54](url)

2021-05-04 17:58 UTC, szh2425 commented
@alexanderkgonzalez When you have a moment, would you be able to  double check/update Kyle permissions to comment in PRs on this repo? He submitted a comment but I can't see it on my end

2021-05-06 01:10 UTC, szh2425 requested changes
Just one more thing and you can merge this PR! Nice work 🎉

2021-05-06 01:10 UTC, szh2425 commented on react_ui/components/SubjectSelect/DeleteForm.js
>    }
You can delete this func! It's not being used anywhere.

2021-05-06 13:30 UTC, szh2425 approved these changes
🎉  Yay! 

This might feel redundant, but once you squash & merge this PR, please start a PR for `dev-kyle` to `dev`! 

Alex and I will do a final overall review of all the changes in dev-kyle, and once we merge into `dev`, we can start user testing!

2021-05-06 13:45 UTC, EndlessThoughts commented on react_ui/actions/subject.js
> +  throw error;
Testing

2021-05-06 13:56 UTC, merged