Final Review for Super user Delete Subject Button
chop-dbhi/biorepo-portal pull request #302
Opened 2021-05-06 14:04 UTC by EndlessThoughts

2021-05-07 15:22 UTC, szh2425 reviewed
Minor changes and you're good!

2021-05-07 15:22 UTC, szh2425 commented on react_ui/reducers/subject.js
> +      });
This state change doesn't happen anywhere, I think you can remove.

2021-05-07 15:22 UTC, szh2425 commented on react_ui/actions/subject.js
> +    .catch(errors => deleteSubjectFailure(errors))
Missing dispatch keyword since deleteSubjectFailure is a redux action: `.catch(errors => dispatch(deleteSubjectFailure(errors)));`

2021-05-07 15:22 UTC, szh2425 commented on react_ui/reducers/subject.js
> +        newFormErrors: {
Similar to above, rename `newFormErrors` to `deleteFormErrors`

2021-05-07 15:22 UTC, szh2425 commented on react_ui/reducers/subject.js
> +        newFormErrors: {
rename `newFormErrors` to `deleteFormErrors` since this is for the deleteSubjectForm

2021-05-07 17:28 UTC, szh2425 commented on react_ui/actions/subject.js
> +    .catch(errors => deleteSubjectFailure(errors))
oh! hmmm okay. I guess we don't really have time to debug...I'm okay with skipping this comment for now since the code works. thanks for testing it and letting me know!

2021-05-07 17:29 UTC, szh2425 approved these changes

2021-05-11 19:48 UTC, EndlessThoughts commented
I was looking at using local state to reduce the use of the redux store. I found that using local state is good for rendering a new window (delete form window) . However, closing the window is difficult (in terms of the cancel button in the new window so far). In order to close the window, I would have to change the state in the previous "parent" component (This is hierarchy of the components: Index -> DeleteForm, DeleteForm -> DeleteConfirmation). I am not sure if we can change the state of a parent component from a child component. 

Please let me know your thoughts.

2021-05-13 13:36 UTC, szh2425 commented
@EndlessThoughts  Updating parent state from child component is possible in react! It would look something like this:  
``` javascript
class Parent extends React.Component {
    constructor(props) {
        this.state = {
              someState: false;      // local state that exists in parent 
         };

        this.handleState = this.handleState.bind(this);
    }

    // This method will be sent to the child component as a prop.
    // Note that this method also takes in a parameter so that the state isn't hard coded in the method.
    handleState(value) {
        this.setState({
            someState: value,
        });
    }

    render() {
        return (
           <div>
                 { /* Render the child component and pass in the handleState function as a prop. */ }
              <Child handleState={this.handleState} />
              <div>{this.state.id}</div>
           </div>
        );
    }
}

// This is the child component. Can be in a new file.
class Child extends React.Component {
    render() {
        return (
            <div>
                {/* The button will execute the handleState function set by the parent component, and update 
                  local state in  parent. */}
                <button onClick={() => this.props.handleState(true)} > button </button>
            </div>
        )
    }
}
```

Does this make sense? And what questions does this raise?

2021-05-13 13:45 UTC, szh2425 commented on react_ui/components/SubjectSelect/index.js
> +          {this.state.testDelete === true ? <DeleteForm /> : <div />}
Missing the method `handleDeleteSubject` as a prop. Should look something like 
```
<DeleteForm handleTheState={this.handleDeleteSubject} />
```

2021-05-13 13:45 UTC, szh2425 commented on react_ui/components/SubjectSelect/index.js
> +    this.setState({testDelete: true});
Hardcoding `true` will set state to true every time the method is called!  Try adding a parameter to the method and setting the state to the parameter instead of a hardcoded value.

2021-05-13 13:59 UTC, EndlessThoughts commented on react_ui/components/SubjectSelect/index.js
> +    this.setState({testDelete: true});
Do you mean adding a const and setting the state to the const?

2021-05-13 14:15 UTC, szh2425 commented on react_ui/components/SubjectSelect/index.js
> +    this.setState({testDelete: true});
Hmm might just be terminology mixup but I'd use `variable` or `parameter` instead of `const` since `const` implies a value that doesn't change. 

If it's the case that you want to use this method to set `testDelete` state to _either_ `true `or `false`, then you'd want the method to take in `true` or `false` as a parameter so that depending on where the function is being called, you can control the state. So redefining the method to look like:
``` javascript
 handleDeleteSubject(value){       // value is the parameter and is either `true` or `false`
    this.setState({testDelete: value});     // set testDelete to the value variable instead of  `true`
 }
```

When you call the `handleDeleteSubject` method in the child component for example, it would look like: 
`this.props.handleDeleteSubject(false)` 

In the parent component, it would be:
`this.handleDeleteSubject(true)`

2021-05-13 15:00 UTC, EndlessThoughts commented on react_ui/components/SubjectSelect/index.js
> +    this.setState({testDelete: true});
<img width="557" alt="Screen Shot 2021-05-13 at 11 00 38 AM" src="https://user-images.githubusercontent.com/55556079/118144438-76a99600-b3da-11eb-8460-ca25405ebe5b.png">

2021-05-13 15:01 UTC, EndlessThoughts commented on react_ui/components/SubjectSelect/index.js
> +    this.setState({testDelete: true});
This may be because the onClick handler is now attempting to change state?

2021-05-13 15:29 UTC, EndlessThoughts commented on react_ui/components/SubjectSelect/index.js
> +    this.setState({testDelete: true});
<img width="552" alt="Screen Shot 2021-05-13 at 11 29 52 AM" src="https://user-images.githubusercontent.com/55556079/118148423-8a56fb80-b3de-11eb-82ea-c710fa5e95e1.png">

2021-05-13 15:30 UTC, EndlessThoughts commented on react_ui/components/SubjectSelect/index.js
> +    this.setState({testDelete: true});
This error also shows up with the new implementation

2021-05-13 18:13 UTC, szh2425 commented on react_ui/components/SubjectSelect/index.js
> +    this.setState({testDelete: true});
@EndlessThoughts  I just made a commit where local state is now working: 31ed21e ; try doing a `git pull` to get the changes on your local branch. 

The reason you're getting this error is because you are calling the function when you pass it in as a prop to the DeleteForm (so updating state while rendering DeleteForm). 
``` javascript
// in index.js:
<DeleteForm handleDeleteSubject={this.handleDeleteSubject()}/> 
  // this initializes the prop but also executes the function at the same time 
  // because () at the end of the method name means you're calling the method.
```

I changed it to: 
``` javascript
 // this just initializes the method as prop - doesn't actually execute it which is what we want 
// during rendering. 
<DeleteForm handleDeleteSubject={this.handleDeleteSubject}/> 
```


And then one other change I had to do was in deleteForm.js. In the onClick method of the cancel button, you call:
```javascript 
onClick={() => this.props.handleDeleteState(false)}
```
but `handleDeleteState` is not defined since you are passing in the prop as `handleDeleteSubject`. So I just updated the function name.

2021-05-13 18:30 UTC, EndlessThoughts commented on react_ui/components/SubjectSelect/index.js
> +    this.setState({testDelete: true});
Interesting...when I was attempting it earlier, I ran into an issue where the console was saying to execute it as a function. Glad it works now! I will do the same for confirmation.

2021-05-13 19:04 UTC, EndlessThoughts commented
I just added the new commits in my attempt to switch the delete confirmation to local state. I am running into an issue with line 47 in DeleteForm because prevent default.

https://github.com/chop-dbhi/biorepo-portal/blob/30bf6aa8eca1a3f6855c48f465fd248836cabc84/react_ui/components/SubjectSelect/DeleteForm.js#L47

2021-05-13 20:25 UTC, EndlessThoughts commented
I'm getting this error after implementing the function that handles setting deleteConfirmationMode.

<img width="553" alt="Screen Shot 2021-05-13 at 4 22 13 PM" src="https://user-images.githubusercontent.com/55556079/118183082-b63aa700-b407-11eb-94e8-4ca16e1a306f.png">

2021-05-18 15:45 UTC, szh2425 requested changes
Minor changes, some of which are cosmetic code changes (sorry about those, I know they can be annoying but makes it easier to read the code later on). 

Have you tried hitting "Cancel" from the DeleteConfirmationPage? It doesn't do anything at the moment. (Hint: DeleteConfirmationMode is correctly being set to false when Cancel is clicked, but what other state needs to be set to false?)

2021-05-18 15:45 UTC, szh2425 commented on react_ui/components/SubjectSelect/index.js
> +      deleteSubjectMode: state.subject.deleteSubjectMode,
`mapStateToProps` is a redux specific function. Since deleteSubjectMode is local state, no need to define it here.

2021-05-18 15:45 UTC, szh2425 commented on react_ui/reducers/subject.js
> +        editSubjectMode: !state.deleteSubjectMode,
Was this accidentally edited? We don't need to account for the state of deleteSubject in actions or reducers since that's specific to redux store.

2021-05-18 15:45 UTC, szh2425 commented on react_ui/reducers/subject.js
> +  deleteSubjectMode: false,
Remove since deleteSubject state is accounted for locally.

2021-05-18 15:45 UTC, szh2425 commented on react_ui/components/SubjectSelect/DeleteForm.js
> +    const { dispatch } = this.props;
Hm, do you know what this line does? 
``` javascript
const { dispatch } = this.props;
```
I see it a lot in most of the function definitions. Is it specific to Redux and if so, do we need it in the components where we're using local state?

2021-05-18 15:45 UTC, szh2425 commented on react_ui/components/SubjectSelect/DeleteForm.js
> +    this.handleDeleteConfirmation();
Why call `handleDeleteConfirmation()` since you're manually setting deleteConfirmationMode state in the if/else below?

2021-05-18 15:45 UTC, szh2425 commented on react_ui/components/SubjectSelect/DeleteForm.js
> +                        defaultValue={{label: this.state.theSubject, value: this.state.chooseSubject}}
Is setting this default value necessary? `theSubject` is not defined anywhere and chooseSubject is set to `{' '}` at the beginning, so default value is not being set to anything specific.

2021-05-18 15:45 UTC, szh2425 commented on react_ui/components/SubjectSelect/DeleteForm.js
> +      deleteSubjectConfirmationMode: state.subject.deleteSubjectConfirmationMode,
Since deleteSubjectConfirmationMode is being stored locally, we don't have to account for it in this redux function.

2021-05-18 15:45 UTC, szh2425 commented on react_ui/actions/record.js
> +
Remove extra space

2021-05-18 15:50 UTC, EndlessThoughts commented on react_ui/components/SubjectSelect/index.js
> -    let row = {};
Visual studio was saying that the line 49 here is unused.

2021-05-18 15:53 UTC, EndlessThoughts commented on react_ui/reducers/subject.js
> +        editSubjectMode: !state.deleteSubjectMode,
This was accidentally edited.

2021-05-18 15:55 UTC, EndlessThoughts commented on react_ui/components/SubjectSelect/DeleteForm.js
> +    this.handleDeleteConfirmation();
As per our previous conversation, you had suggested that I call the function in the handle submit before the conditional that checks for an empty subject.

2021-05-18 16:03 UTC, EndlessThoughts commented on react_ui/components/SubjectSelect/DeleteForm.js
> +    const { dispatch } = this.props;
I believe that this line is specific to redux but it is not necessary when we're dealing with components that are utilizing local state.

2021-05-18 16:06 UTC, EndlessThoughts commented
> Minor changes, some of which are cosmetic code changes (sorry about those, I know they can be annoying but makes it easier to read the code later on).
> 
> Have you tried hitting "Cancel" from the DeleteConfirmationPage? It doesn't do anything at the moment. (Hint: DeleteConfirmationMode is correctly being set to false when Cancel is clicked, but what other state needs to be set to false?)

-

The cancel button in my confirmation page has been working for me. It works on Safari and Chrome. Hmmm...can you try git pull and then let me know if the issue is persisting? @szh2425

2021-05-18 18:14 UTC, szh2425 commented
@EndlessThoughts 🤦‍♀️ sorry about that...I forgot to `git pull` on my local.

2021-05-20 17:15 UTC, szh2425 commented on react_ui/components/SubjectSelect/DeleteForm.js
> +    this.handleDeleteConfirmation();
@EndlessThoughts gotcha. I think I meant that you could call the function within the conditional - like 
```
  if(this.state.chooseSubject.firstName != undefined) {
       handleDeleteConfirmation(true);
    } else{
        handleDeleteConfirmation(false);
       this.setState({deleteSubjectErr: true})  
    }
```

but it's also fine the way it is. We really just need `handleDeleteConfirmation` to be sent as a prop to deleteConfirmation which is the main reason we have it defined as a separate function in the first place.

2021-05-20 17:27 UTC, szh2425 requested changes
One more minor change but this looks good to me in terms of using local state for deleteForm and deleteConfirmation form (although I admit I did a somewhat more perfunctory review this time around).

2021-05-20 17:27 UTC, szh2425 commented on react_ui/components/SubjectSelect/DeleteForm.js
> +    const { dispatch } = this.props;
Remove

2021-06-03 19:12 UTC, merged